#
# Makefile pour generer la bibliotheque de fonctions reseau
#

#
# Constantes
#

SRC=
OBJ=$(SRC:.c=.o)
LIB_NAME=


#
# Cible principale
#

all: $(OBJ)
	@echo ==== LIBSCK ====
#$(AR) $(LIB_NAME) $(OBJ)
	@echo ================


#
# Cible debug
#

debug:


#
# Cible de nettoyage
#

clean:
	@echo
	@echo Debut du nettoyage Socket
	#rm -f *.o $(LIB_NAME)
	@echo Fin du nettoyage Socket
	@echo


#
# Dependance
#

#libsck.o: $(SRC) libsck.h

